token = "" # Токен сообщества ВКонтакте

buttons_text = "vto.pe"
message_text = "d" # Текст сообщения. Если короче 4096 байтов - будет повторён максимальное количество раз

logging_level = "DEBUG"
delay = 0.1
